# Final Merged Application Configuration
application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production
  experimental_mode: false

server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true

logging:
  level: INFO
  format: json
  output: /var/log/app.log

database:
  host: cluster.example.com
  port: 5432
  name: devops_production
  distributed: false

features:
  auto_scaling: enabled
  load_balancer: standard
  backup_enabled: true
  chaos_engineering: disabled

ai_features:
  predictive_scaling: false
  anomaly_detection: false
  auto_optimization: false
  model_version: "v1.0.0"

cloud_providers:
  - aws
  - azure

security:
  zero_trust: enabled
  encryption: AES-256
  audit_logging: basic

development:
  enabled: false
  port: 3000
  hot_reload: false
  debug_mode: false
  mock_apis: false
